config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :categories, only: :show
  
  devise_for :admins
  devise_scope :admin do
    get 'admin', :to => 'devise/sessions#new'
  end
  
  root 'books#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true,length: { maximum: 255 }
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  
  def to_param
    name
  end
  
  default_scope { order('name ASC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :get_categories
  
  def get_categories
    @categories = Category.all
    category = Category.find_by_name(params[:id])
    @category_id = category.id if category.present?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  respond_to :html

  def index
    @books = Book.all.order('name').paginate(:page => params[:page])
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    @book.destroy
    respond_with(@book)
  end
  
  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:name, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    category_id = Category.find_by_name(params[:id]).id
    @books = Book.where(category_id: category_id).order(:name).page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url
    gravatar_id = Digest::MD5::hexdigest(ENV['EMAIL']).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
  
  def copyright_year
    case Time.now.year
    when 2015 then '2015'
    else
      '2015 - ' + Time.now.year.to_s
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_name(id)
    Category.find(id).name
  end
end

app/views/books/_form.html.erb
<%= bootstrap_form_for @book do |f| %>

    <% if @book.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= f.text_field :name %>
  <%= f.select :category_id, Category.all.map{|t| [t.name, t.id]} %>

  <%= f.primary 'Submit', :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            books_path, :class => 'btn btn-default' %>

<% end %>

app/views/books/_list.html.erb
<% @books.each do |book| %>
  <div class="alert alert-info">
    <div style="float: left;"><%= book.name %></div>
    <% if admin_signed_in? %>
      <div class="text-right">
        <%= link_to 'Edit', edit_book_path(book), :class => "btn btn-success btn-xs" %>
        <%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %>
      </div>
    <% end %>
    <div style="clear: both;"></div>
    <hr>
    <%= link_to category_name(book.category_id), category_path(category_name(book.category_id)) %>
  </div>
<% end %>
<%= will_paginate @books, renderer: BootstrapPagination::Rails %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%= render 'list' %>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @book.name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= category_name(@book.category_id) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>
<% if admin_signed_in? %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_book_path(@book), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              book_path(@book),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>

app/views/categories/index.html.erb
<%= render 'books/list' %>

app/views/categories/show.html.erb
<%= render 'books/list' %>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; <%= link_to "zhangjingqiang", ENV['ABOUT_ME'] %> <%= copyright_year %></p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Qiang Books</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <% @categories.each do |category| %>
          <li<%= ' class=active' if category.id == @category_id %>>
            <a href="<%= category_path(category) %>"><%= category.name %></a>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li><%= link_to 'New Book', new_book_path %></li>
          <li><%= link_to 'Logout', destroy_admin_session_path, :method=>'delete' %></li>
        <% else %>
          <li><%= link_to image_tag(avatar_url, :size => "20x20"), ENV['ABOUT_ME'], :class => "navbar-link" %></li>
        <% end %>
      </ul>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</nav><!-- /.navbar -->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Qiang Books">
  <meta name="author" content="zhangjingqiang">
  
  <title>Qiang Books</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <hr>
    <%= render 'layouts/footer' %>
  </div> <!-- /container -->
</body>
</html>